FROM ghcr.io/rocker-org/shiny:4.5
LABEL Description="Docker image for shiny-flyer"
LABEL authors="Roy Francis"
LABEL org.opencontainers.image.source="https://github.com/royfrancis/shiny-flyer"
ARG QUARTO_VERSION="1.8.26"

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get clean \
    && apt-get install -y libxml2-dev libssl-dev libcurl4-openssl-dev libudunits2-dev curl \
    && curl -o quarto-linux-amd64.deb -L https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb \
    && apt-get install -y ./quarto-linux-amd64.deb \
    && rm -rf ./quarto-linux-amd64.deb \
    && rm -rf /var/lib/apt/lists/* \
    && install2.r --error --skipinstalled markdown remotes colourpicker shinyWidgets bsicons \
    && Rscript -e 'remotes::install_github("rstudio/bslib");remotes::install_github("quarto-dev/quarto-r")' \
    && rm -rf /tmp/downloaded_packages

RUN rm -rf /srv/shiny-server/*
COPY . /srv/shiny-server/
# COPY shiny-server.config /etc/shiny-server/shiny-server.conf

# Ensure that the expected user is present in the container
RUN if id shiny &>/dev/null && [ "$(id -u shiny)" -ne 999 ]; then \
        userdel -r shiny; \
        id -u 999 &>/dev/null && userdel -r "$(id -un 999)"; \
    fi; \
    useradd -u 999 -m -s /bin/bash shiny; \
    chown -R shiny:shiny /srv/shiny-server/ /var/lib/shiny-server/ /var/log/shiny-server/

USER shiny
EXPOSE 3838

CMD ["/usr/bin/shiny-server"]
